module.exports = {
  menu: "Меню",
  menu_write_post: "Написать пост",
  menu_posts: "Посты",
  menu_drafts: "Черновики",
  menu_preferences: "Настройки",
  menu_about: "О Chad",
  channels: "Каналы",
  channels_add_channel: "Добавить канал",
  bot_refresh: "Обновить",
  bot_change: "Изменить",
  bot_remove: "Удалить",
  bot_set: "Указать админ бота",
  settings: "Параметры",
  settings_formatting_styles: "Стиль форматирования",
  settings_none: "Нет",
  settings_html: "HTML",
  settings_markdown: "Markdown",
  settings_link: "Ссылка",
  settings_bold: "Жирный",
  settings_italic: "Курсив",
  post_test: "Текст поста",
  post_send: "Отправить",
  post_save_draft: "Сохранить черновик",
  post_cancel: "Отмена",
  post_settings: "Параметры",
  post_settings_ok: "OK",
  post_settings_disable_link_preview: "Отключить предпросмотр ссылок",
  post_settings_disable_notification: "Отключить уведомление",
  preview: "Предпросмотр",
  loading: "Загрузка...",
  d_about: "О Chad",
  d_about_close: "Закрыть",
  d_preferences: "Настройки",
  d_preferences_language: "Язык",
  d_preferences_dark_theme: "Тёмная тема",
  d_preferences_ok: "OK",
  d_set_admin_bot: "Указать админ бота",
  d_set_admin_bot_token: "Ключ бота",
  d_set_admin_bot_cancel: "Отмена",
  d_set_admin_bot_save: "Сохранить",
  d_add_channel: "Добавить канал",
  d_add_channel_name: "Название канала",
  d_add_channel_name_placeholder: "Мой канал",
  d_add_channel_username: "Никнейм канала",
  d_add_channel_cancel: "Отмена",
  d_add_channel_save: "Сохранить",
  d_insert_link: "Вставить ссылку",
  d_insert_link_title: "Название ссылки",
  d_insert_link_url: "Адрес ссылки",
  d_insert_link_cancel: "Отмена",
  d_insert_link_save: "Сохранить",
  posts_delete: "Удалить",
  posts_edit: "Изменить",
  posts_empty: "Список пуст",
  drafts_delete: "Удалить",
  drafts_edit: "Изменить",
  drafts_send: "Отправить",
  drafts_empty: "Список пуст"
};