module.exports = {
  menu: 'Menu',
  menu_write_post: 'Write post',
  menu_posts: 'Posts',
  menu_drafts: 'Drafts',
  menu_preferences: 'Preferences',
  menu_about: 'About Chad',

  channels: 'Channels',
  channels_add_channel: 'Add channel',

  bot_refresh: 'Refresh',
  bot_change: 'Change',
  bot_remove: 'Remove',
  bot_set: 'Set admin bot',

  settings: 'Settings',
  settings_formatting_styles: 'Formatting styles',
  settings_none: 'None',
  settings_html: 'HTML',
  settings_markdown: 'Markdown',
  settings_link: 'Link',
  settings_bold: 'Bold',
  settings_italic: 'Italic',

  post_test: 'Post text',
  post_send: 'Send',
  post_save_draft: 'Save draft',
  post_cancel: 'Cancel',

  post_settings: 'Settings',
  post_settings_ok: 'OK',
  post_settings_disable_link_preview: 'Disable link preview',
  post_settings_disable_notification: 'Disable notification',

  preview: 'Preview',

  loading: 'Loading...',

  d_about: 'About Chad',
  d_about_close: 'Close',

  d_preferences: 'Preferences',
  d_preferences_language: 'Language',
  d_preferences_dark_theme: 'Dark theme',
  d_preferences_default_postwrite: 'Post options',
  d_preferences_general: 'General',
  d_preferences_ok: 'OK',

  d_set_admin_bot: 'Set admin bot',
  d_set_admin_bot_token: 'Bot token',
  d_set_admin_bot_cancel: 'Cancel',
  d_set_admin_bot_save: 'Save',

  d_add_channel: 'Add channel',
  d_add_channel_name: 'Channel name',
  d_add_channel_name_placeholder: 'My channel',
  d_add_channel_username: 'Channel username',
  d_add_channel_cancel: 'Cancel',
  d_add_channel_save: 'Save',

  d_insert_link: 'Insert link',
  d_insert_link_title: 'Link title',
  d_insert_link_url: 'Link url',
  d_insert_link_cancel: 'Cancel',
  d_insert_link_save: 'Save',

  posts_delete: 'Delete',
  posts_edit: 'Edit',
  posts_empty: 'Empty list',

  drafts_delete: 'Delete',
  drafts_edit: 'Edit',
  drafts_send: 'Send',
  drafts_empty: 'Empty list',

  tmenu_edit: 'Edit',
  tmenu_edit_undo: 'Undo',
  tmenu_edit_redo: 'Redo',
  tmenu_edit_cut: 'Cut',
  tmenu_edit_copy: 'Copy',
  tmenu_edit_paste: 'Paste',
  tmenu_edit_delete: 'Delete',
  tmenu_edit_selectall: 'Select all',

  tmenu_view: 'View',
  tmenu_view_reload: 'Reload',
  tmenu_view_toggledevtools: 'Toggle Developer Tools',
  tmenu_view_resetzoom: 'Reset zoom',
  tmenu_view_zoomin: 'Zoom in',
  tmenu_view_zoomout: 'Zoom out',
  tmenu_view_togglefullscreen: 'Enter Full Screen',

  tmenu_window: 'Window',
  tmenu_window_minimize: 'Minimize',
  tmenu_window_close: 'Close',
  tmenu_window_zoom: 'Zoom',
  tmenu_window_front: 'Bring All to Front',

  tmenu_help: 'Help',
  tmenu_help_learnmore: 'Learn More',

  tmenu_app_about: 'About Chad',
  tmenu_app_checkforupdates: 'Check for updates',
  tmenu_app_reportbugs: 'Report bugs',
  tmenu_app_services: 'Services',
  tmenu_app_hide: 'Hide Chad',
  tmenu_app_hideothers: 'Hide others',
  tmenu_app_unhide: 'Show all',
  tmenu_app_quit: 'Quit Chad',

  alert_select_formatting_style: 'Select formatting style',
  alert_select_channel_to_send: 'Select channel(s) to send post',
  alert_add_admin_bot: 'Add Admin bot',
  alert_post_text_empty: 'Post text is empty',
  alert_something_wrong: 'Something went wrong',
  alert_channel_name_short: 'Channel name is too short',
  alert_invalid_channel_name: 'Invalid channel username',
  alert_invalid_token: 'Invalid token',
  alert_invalid_token_format: 'Invalid token format',
  alert_cant_find_bot: 'Can\'t find bot with this token',

  snackbar_draft_saved: 'Draft saved!',

  update: 'Update',
  update_new: 'A newer version $newVer is available!',
  update_new_detail: 'Detail',
  update_new_cancel: 'Cancel',
  update_no: 'No Updates',
  update_no_text: 'Current version $version is already up to date!',
  update_no_ok: 'OK',
};
