module.exports = {
  menu: 'Меню',
  menu_write_post: 'Написать пост',
  menu_posts: 'Посты',
  menu_drafts: 'Черновики',
  menu_preferences: 'Настройки',
  menu_about: 'О Chad',

  channels: 'Каналы',
  channels_add_channel: 'Добавить канал',

  bot_refresh: 'Обновить',
  bot_change: 'Изменить',
  bot_remove: 'Удалить',
  bot_set: 'Указать админ бота',

  settings: 'Параметры',
  settings_formatting_styles: 'Стиль форматирования',
  settings_none: 'Нет',
  settings_html: 'HTML',
  settings_markdown: 'Markdown',
  settings_link: 'Ссылка',
  settings_bold: 'Жирный',
  settings_italic: 'Курсив',

  post_test: 'Текст поста',
  post_send: 'Отправить',
  post_save_draft: 'Сохранить черновик',
  post_cancel: 'Отмена',

  post_settings: 'Параметры',
  post_settings_ok: 'OK',
  post_settings_disable_link_preview: 'Отключить предпросмотр ссылок',
  post_settings_disable_notification: 'Отключить уведомление',

  preview: 'Предпросмотр',

  loading: 'Загрузка...',

  d_about: 'О Chad',
  d_about_close: 'Закрыть',

  d_preferences: 'Настройки',
  d_preferences_language: 'Язык',
  d_preferences_dark_theme: 'Тёмная тема',
  d_preferences_default_postwrite: 'Параметры поста',
  d_preferences_general: 'Основные',
  d_preferences_ok: 'OK',

  d_set_admin_bot: 'Указать админ бота',
  d_set_admin_bot_token: 'Ключ бота',
  d_set_admin_bot_cancel: 'Отмена',
  d_set_admin_bot_save: 'Сохранить',

  d_add_channel: 'Добавить канал',
  d_add_channel_name: 'Название канала',
  d_add_channel_name_placeholder: 'Мой канал',
  d_add_channel_username: 'Никнейм канала',
  d_add_channel_cancel: 'Отмена',
  d_add_channel_save: 'Сохранить',

  d_insert_link: 'Вставить ссылку',
  d_insert_link_title: 'Название ссылки',
  d_insert_link_url: 'Адрес ссылки',
  d_insert_link_cancel: 'Отмена',
  d_insert_link_save: 'Сохранить',

  posts_delete: 'Удалить',
  posts_edit: 'Изменить',
  posts_empty: 'Список пуст',

  drafts_delete: 'Удалить',
  drafts_edit: 'Изменить',
  drafts_send: 'Отправить',
  drafts_empty: 'Список пуст',

  tmenu_edit: 'Редактирование',
  tmenu_edit_undo: 'Шаг назад',
  tmenu_edit_redo: 'Шаг вперед',
  tmenu_edit_cut: 'Вырезать',
  tmenu_edit_copy: 'Копировать',
  tmenu_edit_paste: 'Вставить',
  tmenu_edit_delete: 'Очистить',
  tmenu_edit_selectall: 'Выделить все',

  tmenu_view: 'Просмотр',
  tmenu_view_reload: 'Обновить',
  tmenu_view_toggledevtools: 'Открыть панель разработчика',
  tmenu_view_resetzoom: 'Реальный размер',
  tmenu_view_zoomin: 'Увеличить',
  tmenu_view_zoomout: 'Уменьшить',
  tmenu_view_togglefullscreen: 'Во весь экран',

  tmenu_window: 'Окно',
  tmenu_window_minimize: 'Свернуть',
  tmenu_window_close: 'Закрыть',
  tmenu_window_zoom: 'Увеличить',
  tmenu_window_front: 'Все на передний план',

  tmenu_help: 'Помощь',
  tmenu_help_learnmore: 'Подробнее',

  tmenu_app_about: 'О Chad',
  tmenu_app_checkforupdates: 'Проверить обновления',
  tmenu_app_reportbugs: 'Сообщить об ошибке',
  tmenu_app_services: 'Сервисы',
  tmenu_app_hide: 'Скрыть Chad',
  tmenu_app_hideothers: 'Скрыть другие',
  tmenu_app_unhide: 'Показать все',
  tmenu_app_quit: 'Выйти из Chad',

  alert_select_formatting_style: 'Выберите стиль форматирования',
  alert_select_channel_to_send: 'Выберите канал(ы) для отправки поста',
  alert_add_admin_bot: 'Добавьте админ бота',
  alert_post_text_empty: 'Текст поста пуст',
  alert_something_wrong: 'Что-то пошло не так...',
  alert_channel_name_short: 'Имя канала слишком короткое',
  alert_invalid_channel_name: 'Неверный никнейм канала',
  alert_invalid_token: 'Неверный ключ',
  alert_invalid_token_format: 'Неверный формат ключа',
  alert_cant_find_bot: 'Бот с этим ключом не найден',

  snackbar_draft_saved: 'Черновик сохранен!',

  update: 'Обновление',
  update_new: 'Новая версия $newVer уже доступна!',
  update_new_detail: 'Подробнее',
  update_new_cancel: 'Отмена',
  update_no: 'Нет обновлений',
  update_no_text: 'Текущая версия $version самая новая!',
  update_no_ok: 'OK',
};
